Repository Automattic/themes-workspace, pull requests merged in 2020-04, with the labels that each got.

#38 Varya: Clean up responsive logic
  varya/assets/css/style-editor.css
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/sass/structure/_responsive-logic.scss
  varya/style-rtl.css
  varya/style.css
Labels: work in progress

#39 Varya: Remove subnav character indents and replace with more straightforward spacing.
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, enhancement

#46 Varya: Minor font + entry footer cleanup
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/entry/_config.scss
  varya/assets/sass/components/entry/_meta.scss
  varya/assets/sass/components/pagination/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#45 Varya: Minor header cleanup
  varya/assets/css/variables.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/header/_config.scss
  varya/assets/sass/components/header/_header-branding.scss
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/functions.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#42 Varya: Update dropdown arrows to match comps (alternative)
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/inc/template-functions.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#47 Varya: Clean up the header on mobile
  varya/assets/css/variables.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/header/_config.scss
  varya/assets/sass/components/header/_header-branding.scss
  varya/assets/sass/structure/_vertical-margins.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#48 Varya: Adjust global spacing unit to match comps
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
Labels: enhancement

#53 Varya: Refine the post comments
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/comments/_comment-form.scss
  varya/assets/sass/components/comments/_comments.scss
  varya/assets/sass/elements/_config.scss
  varya/assets/sass/elements/_forms.scss
  varya/comments.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#61 Varya: Clean up desktop menu alignment
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/assets/sass/vendors/woocommerce/components/_mini-cart.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#69 Remove blockbase theme
  blockbase/LICENSE
  blockbase/README.md
  blockbase/block-template-parts/footer.html
  blockbase/block-template-parts/header.html
  blockbase/block-templates/index.html
  blockbase/block-templates/singular.html
  blockbase/css/editor/editor-custom.css
  blockbase/css/editor/variables.css
  blockbase/css/front-end/normalize.css
  blockbase/css/front-end/style-base.css
  blockbase/css/front-end/style-blocks.css
  blockbase/css/front-end/style-custom.css
  blockbase/experimental-theme.json
  blockbase/functions.php
  blockbase/index.php
  blockbase/readme.txt
  blockbase/style-editor.css
  blockbase/style.css
Labels: [Theme] Blockbase

#64 Varya: Rename "menu-1" to "primary"
  varya/functions.php
  varya/header.php
  varya/inc/template-functions.php
  varya/inc/woocommerce.php
Labels: enhancement

#68 Varya: Adjust the appearance of the sticky flag
  varya/assets/sass/pages/_posts-and-pages.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#62 [Varya] Remove WooCommerce cart checkbox
  varya/inc/woocommerce.php
Labels: enhancement

#65 Varya: Update social icons to match Gutenberg's social links block
  varya/assets/sass/style.scss
  varya/classes/class-varya-svg-icons.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#67 Varya: Allow social navigation items to wrap
  varya/assets/sass/components/header/_social-navigation.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#59 Varya: Removing light and dark border-color and variables.
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/comments/_comments.scss
  varya/assets/sass/vendors/woocommerce/pages/_single-product.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#63 Varya: Correct menu animation jump when WooCommerce and Admin Bar are active
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#81 Update readme file
  varya/README.md
Labels: documentation

#83 Varya: Refine mobile heading spacing
  varya/assets/sass/structure/_vertical-margins.scss
  varya/inc/template-functions.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#82 Varya: Update selection color
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
Labels: enhancement

#86 Use the theme's max-width in the editor
  varya/assets/css/style-editor.css
  varya/assets/sass/base/_editor.scss
Labels: bug

#91 Varya: Adjust search form layout
  varya/assets/sass/elements/_forms.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#75 Varya: Fix button styles
  varya/assets/css/style-editor.css
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/blocks/button/_config.scss
  varya/assets/sass/blocks/button/_editor.scss
  varya/assets/sass/blocks/button/_style.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/style-rtl.css
  varya/style.css
Labels: bug

#111 Varya: update pagination treatment and utilize existing pagination variables
  varya/assets/css/variables.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/pagination/_config.scss
  varya/assets/sass/components/pagination/_style.scss
  varya/assets/sass/variables.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#114 Update link underline in the editor
  varya/assets/css/style-editor.css
  varya/assets/sass/base/_editor.scss
Labels: [Theme] Varya, bug

#109 Update heading line height
  varya/assets/css/style-editor.css
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/blocks/heading/_config.scss
  varya/assets/sass/blocks/heading/_editor.scss
  varya/assets/sass/blocks/heading/_style.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/style-rtl.css
  varya/style.css
Labels: bug

#112 Varya: Refine the search block styles
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/_editor.scss
  varya/assets/sass/blocks/_style.scss
  varya/assets/sass/blocks/search/_editor.scss
  varya/assets/sass/blocks/search/_style.scss
  varya/assets/sass/components/widgets/_style.scss
  varya/assets/sass/elements/_forms.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#117 Varya: Fix line height in large quote block.
  varya/assets/css/style-editor.css
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/blocks/quote/_config.scss
  varya/assets/sass/blocks/quote/_editor.scss
  varya/assets/sass/blocks/quote/_style.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug

#118 Varya: Fixes file block button appearance.
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/_editor.scss
  varya/assets/sass/blocks/button/_style.scss
  varya/assets/sass/blocks/file/_editor.scss
  varya/assets/sass/blocks/file/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug

#119 Varya: Fix alignment issues in pullquote & video blocks.
  varya/assets/sass/blocks/pullquote/_style.scss
  varya/assets/sass/blocks/video/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug

#121 Varya: Add support for Verse block.
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/_editor.scss
  varya/assets/sass/blocks/_style.scss
  varya/assets/sass/blocks/verse/_editor.scss
  varya/assets/sass/blocks/verse/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug

#122 Varya: Fix pullquote text-alignments.
  varya/assets/sass/blocks/pullquote/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug

#123 Fix margins on left and right aligned blocks
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/utilities/_editor.scss
Labels: bug

#115 Update Varya Elevation
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, enhancement

#95 Varya: try adding gradient preset
  varya/assets/css/style-editor.css
  varya/assets/sass/base/_style.scss
  varya/assets/sass/blocks/utilities/_editor.scss
  varya/assets/sass/blocks/utilities/_style.scss
  varya/functions.php
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, enhancement

#130 Varya: Add nav block styles
  varya/assets/css/style-editor.css
  varya/assets/css/variables-editor.css
  varya/assets/sass/blocks/_editor.scss
  varya/assets/sass/blocks/_style.scss
  varya/assets/sass/blocks/navigation/_editor.scss
  varya/assets/sass/blocks/navigation/_style.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/variables-editor.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#127 Varya: Fix image alingment issue and code tidying.
  varya/assets/css/style-editor.css
  varya/assets/sass/base/_editor.scss
  varya/assets/sass/blocks/button/_editor.scss
  varya/assets/sass/blocks/utilities/_editor.scss
Labels: bug

#131 Add stripe gradient preset (#92)
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/utilities/_editor.scss
  varya/assets/sass/blocks/utilities/_style.scss
  varya/functions.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#108 Add tiny font size styles
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/utilities/_editor.scss
  varya/assets/sass/blocks/utilities/_style.scss
  varya/functions.php
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug
