Repository Automattic/themes-workspace, pull requests merged in 2020-05, with the labels that each got.

#132 Varya: Use variables in gradient presets
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/utilities/_editor.scss
  varya/assets/sass/blocks/utilities/_style.scss
  varya/functions.php
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#135 Varya: Set max width of author bio
  varya/assets/sass/components/entry/_author-bio.scss
  varya/style-rtl.css
  varya/style.css
  varya/template-parts/post/author-bio.php
Labels: bug

#144 Varya: fix custom color class bug
  varya/classes/class-varya-custom-colors.php
Labels: bug

#138 Varya: add custom color contrast warnings
  varya/assets/js/customizer-validate-wcag-color-contrast.js
  varya/assets/sass/style.scss
  varya/classes/class-varya-custom-colors.php
  varya/readme.txt
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#145 Clean up footer menu
  varya/assets/sass/components/footer/_footer-branding.scss
  varya/assets/sass/components/footer/_footer-navigation.scss
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, bug

#126 Clean version of #85
  varya/assets/css/print.css
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/js/primary-navigation.js
  varya/assets/sass/blocks/button/_style.scss
  varya/assets/sass/blocks/cover/_style.scss
  varya/assets/sass/blocks/file/_style.scss
  varya/assets/sass/blocks/pullquote/_style.scss
  varya/assets/sass/blocks/separator/_style.scss
  varya/assets/sass/blocks/video/_style.scss
  varya/assets/sass/child-theme/_extra-child-theme.scss
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/assets/sass/print.scss
  varya/assets/sass/structure/_responsive-logic.scss
  varya/assets/sass/vendors/woocommerce/components/_mini-cart.scss
  varya/classes/class-varya-walker-comment.php
  varya/functions.php
  varya/header.php
  varya/image.php
  varya/inc/back-compat.php
  varya/inc/customizer.php
  varya/inc/template-functions.php
  varya/inc/template-tags.php
  varya/inc/woocommerce.php
  varya/page.php
  varya/single.php
  varya/style-rtl.css
  varya/style.css
  varya/template-parts/header/site-branding.php
  varya/template-parts/post/discussion-meta.php
Labels: enhancement

#147 Varya: Update style.css header
  varya/assets/sass/child-theme/style-child-theme.scss
  varya/assets/sass/style.scss
  varya/readme.txt
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, enhancement

#148 Varya: Change primary color from red to green
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
  varya/classes/class-varya-custom-colors.php
  varya/functions.php
  varya/screenshot.png
Labels: [Theme] Varya, enhancement

#52 Update Varya Icons
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/sass/components/header/_primary-navigation.scss
  varya/assets/sass/style.scss
  varya/assets/sass/vendors/woocommerce/components/_mini-cart.scss
  varya/classes/class-varya-svg-icons.php
  varya/header.php
  varya/inc/template-functions.php
  varya/inc/template-tags.php
  varya/inc/woocommerce.php
  varya/readme.txt
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, enhancement

#150 Varya: Update theme screenshot and credit lines
  varya/assets/sass/style.scss
  varya/readme.txt
  varya/screenshot.png
  varya/style-rtl.css
  varya/style.css
Labels: [Theme] Varya, enhancement

#151 Varya: Fix quote padding and borders
  varya/assets/sass/blocks/quote/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#152 Add max-width rules for featured images.
  varya/assets/sass/components/entry/_post-thumbnail.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#154 Varya: Fix comment form submit button
  varya/assets/sass/components/comments/_comment-form.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#153 Varya: Update text selection color.
  varya/assets/css/variables-editor.css
  varya/assets/css/variables.css
  varya/assets/sass/abstracts/_config.scss
  varya/assets/sass/child-theme/variables-editor.css
  varya/assets/sass/child-theme/variables.css
Labels: bug

#149 Varya: Use correct font styles for the nav block.
  varya/assets/css/style-editor.css
  varya/assets/sass/blocks/navigation/_editor.scss
  varya/assets/sass/blocks/navigation/_style.scss
  varya/style-rtl.css
  varya/style.css
Labels: bug

#155 Clean up WooCommerce Tabs & Comment Form
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/sass/vendors/woocommerce/components/_product-tabs.scss
  varya/assets/sass/vendors/woocommerce/components/_reviews.scss
Labels: bug

#156 Varya: adjust comment form field CSS
  varya/assets/sass/components/comments/_comment-form.scss
  varya/style-rtl.css
  varya/style.css
Labels: enhancement

#157 Varya: Remove flex-basis rule from woocommerce comments
  varya/assets/css/style-woocommerce-rtl.css
  varya/assets/css/style-woocommerce.css
  varya/assets/sass/vendors/woocommerce/components/_reviews.scss
Labels: enhancement
